version: '3'
services:

  node-app:
    build: 
      context: .
      target: development
    volumes: 
      - ./src:/app/src:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - node-app
      
volumes:
  mongo-db:
